name: RKR
version: 1.0.0
description: Rival Kingdoms Reloaded Central Infrastructure Plugin
author: Stryker_
authors: [EUFlux, Zxios] 
 
main: net.link404.RKR.Main
database: false
 
commands:
  rkr:
    description: Basic command to RKR. Displays available commands.
    permission: rkr.use
    usage: /rkr
  "rkr help":
    description: Displays available time.
    permission: rkr.use
    usage: /rkr help
  "rkr set":
    description: Sets a flag for a team.
    permission: rkr.use
    usage: /rkr set
  "rkr hello":
    description: Debug command. Tests commands status.
    permission: rkr.use
    usage: /rkr hello