 name: RKR
 version: 1.0.0
 description: Rival Kingdoms Reloaded Central Infrastructure Plugin
 author: Stryker_
 authors: [EUFlux, Zxios] 
 
 main: net.link404.RKR.Main
 database: false
 
 commands:
   rkr:
     description: Basic command to RKR.
     permission: rkr.use